Blog-template issue(code block)
Nectbox/nectbox-landing-page pull request #1
Opened 2021-02-16 23:03 UTC by enyelsequeira

I was able to render most things, to the blog template, but I am having a hard time figuring out how to render the code block because in gatsby the way they render things is like this <p><code>value</code></p>
if you can take a look at it, will be great, otherwise, I am going to keep trying in the meantime.

2021-02-17 12:48 UTC, Kerosz commented
I was looking briefly over the things and there are couple of things that needs to be changed.

1. The `blog` component you have in the `components` just returns a div with a link in it. To me doesn't make a whole lot of sense to have a component that just returns a normal link, then having a blog page that just returns that component. So just move that code from the blog components to blog pages. ( https://github.com/Nectbox/nectbox-landing-page/blob/blog/src/components/blog/index.tsx )
2. I have used `kebab case` ( some-file.ts ) instead of `camel case` ( someFile.ts ) for the entire condebase, it is a personal preference but because it is used in all the other files try to use that instead of the camel case.
3. You will probably have to move the hooks folder into the src so we have a single folder in case we decide to add more hooks later on.

I will leave the debugging and solving the blog problems to you until I get to that part, if you cannot figure it out until then we can have a look at it

2021-02-17 17:12 UTC, enyelsequeira commented
Hey, I made the changes asked. Still trying to figure out how to deal with code, block. if you that I've changed the code from `blog` component to be a `blog-card`, makes more sense that way the page itself just renders that component

2021-02-17 18:25 UTC, Kerosz requested changes
Alright, I opened an issue for it here ( https://github.com/Nectbox/nectbox-landing-page/issues/3 ). Please refer to the issue with anything related to the code blocks rendering.

Keep me updated on how it goes

2021-02-25 18:08 UTC, Kerosz approved these changes

2021-02-25 18:29 UTC, merged